### ISSUE TITLE
Fix titles in Classes Wiki page

### ISSUE THREAD

**Issue by FoksVHox** [OGL-Development/lua-plus-plus#12]
Remove the quote (`"`) in the title: https://github.com/OGL-Development/lua-plus-plus/wiki/Classes#get--set-methods
Remove the quotes (`"`) and capitalize the title https://github.com/OGL-Development/lua-plus-plus/wiki/Classes#wip-static-class-functions

**Comment by NoSharp** [comment]
Wiki's been amended.
