### ISSUE TITLE
Change get & set methods

### ISSUE THREAD

**Issue by FoksVHox** [OGL-Development/lua-plus-plus#6]
I'd like to request the get & set methods are getting a better way to write them.

I've read the documentation on LPP and I like how it is written, however, I'd like to see some changes.
```lua
class cat
    name {get set}
    age  {get set}
    type {get }

    constructor(name)
        self.name = name
    end

    function isCat()
        return true
    end

    static function coolCat()
        return "coolCat!"
    end
end

local thomas = new cat("Thomas")
thomas:set_age(50)
thomas:set_name("Thomas v2")
print(thomas:isCat()) - outputs -> true
print(thomas:get_name()) - outputs -> "Thomas v2"
print(thomas:get_age()) - outputs -> 5
```

I'd like to see that the get & set method would see like this:
```lua
thomas:setAge(50)
thomas:setName("Thomas v2")
print(thomas:isCat()) - outputs -> true
print(thomas:getName()) - outputs -> "Thomas v2"
print(thomas:getAge()) - outputs -> 5
```
If you ask me this looks a lot cleaner.

**Comment by JustPlayerDE** [comment]
I can agree but there may be a reason why they decided to use snake_case for it

**Comment by FoksVHox** [comment]
> I can agree but there may be a reason why they decided to use snake_case for it

There might, there might not ;)

**Comment by NoSharp** [comment]
This would be a language change coming in 1.1.1

**Comment by NoSharp** [comment]
Implemented, Closing.
